CREATE TABLE dm_dimensiones_flexibles (
    nodo_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nodo_padre_id     NUMBER, -- Autoreferencia “n” niveles
    nombre_dimension  VARCHAR2(100) NOT NULL, -- Ej: 'Desarrollo Tecnológico', 'Adulto Mayor'
    codigo_clasificador VARCHAR2(50),         -- Ej: 'PT-01', 'GE-01', 'Nivel 1'
    descripcion_nodo  VARCHAR2(300) NOT NULL, -- Nombre del pilar, subtema o acción
    codigo_rango_edad VARCHAR2(50),          -- Opcional: Solo para el último nivel (hoja)
    grupo_etario      VARCHAR2(100),  -- Opcional: grupo etario
    CONSTRAINT fk_nodo_padre FOREIGN KEY (nodo_padre_id) REFERENCES dm_dimensiones_flexibles(nodo_id) ON DELETE CASCADE
);
